
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/oxi-moron/IDEA/clion-2023.2.2/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.5.5-1-MANJARO - x86_64
...
